### PR TITLE
Fix warnings with latest leiningen

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
This resolves these warnings we see when running leinging:
```
09:34:25 sellout:puppetserver justin (6.0.x *%<>) ‖ lein version
...snip....
Tried to load org.apache.httpcomponents/httpcore version 4.1.2 but 4.4.6 was already loaded.
Tried to load org.apache.httpcomponents/httpclient version 4.1.2 but 4.5.3 was already loaded.
Tried to load org.apache.maven.wagon/wagon-http version 2.2 but 3.0.0 was already loaded.
Tried to load commons-codec version 1.4 but 1.9 was already loaded.
Tried to load org.codehaus.plexus/plexus-utils version 3.0 but 3.1.0 was already loaded.
Tried to load org.codehaus.plexus/plexus-component-annotations version 1.5.5 but 1.7.1 was already loaded.
Tried to load org.jsoup/jsoup version 1.6.1 but 1.7.2 was already loaded.
Tried to load org.tcrawley/dynapath version 0.2.3 but 1.0.0 was already loaded.
Tried to load org.codehaus.plexus/plexus-interpolation version 1.14 but 1.24 was already loaded.
Tried to load commons-io version 2.0.1 but 2.6 was already loaded.
Tried to load com.cemerick/pomegranate version 0.3.1 but 1.1.0 was already loaded.
Tried to load org.apache.maven/maven-repository-metadata version 3.0.4 but 3.5.3 was already loaded.
Tried to load org.apache.maven.wagon/wagon-provider-api version 2.2 but 3.0.0 was already loaded.
Tried to load commons-logging version 1.1.1 but 1.2 was already loaded.
Tried to load org.apache.maven/maven-model-builder version 3.0.4 but 3.5.3 was already loaded.
Tried to load org.apache.maven/maven-model version 3.0.4 but 3.5.3 was already loaded.
...snip...
Leiningen 2.9.1 on Java 1.8.0_161 Java HotSpot(TM) 64-Bit Server VM

09:36:46 sellout:puppetserver justin (6.0.x *%<>) ‖
```

**Comment by achin** [comment]
Thanks for the pull request, @justinstoller. I'm not familiar with this part of leiningen. lein-parent uses pomegranate and plexus-utils during its runtime. Is it appropriate to put them in the dev profile?

It seems that way from your warnings, but I wanted to double-check.

**Comment by justinstoller** [comment]
(btw, Maggie is a coworker of mine that I asked to triple check us)

**Comment by achin** [comment]
Thanks, Justin and Maggie. I'll merge the pull request and cut a release over the weekend.

**Comment by achin** [comment]
Merged and released. Thanks again.

https://clojars.org/lein-parent/versions/0.3.7

**Comment by justinstoller** [comment]
Thank you!

**Pull request merged**
